In [2]:
import numpy as np
data = np.array([20,30,40,50,60])

mean = np.mean(data)
std_dev = np.std(data)

print("Mean:",mean)
print("Standard Deviation:",std_dev)

Mean: 40.0
Standard Deviation: 14.142135623730951


In [8]:
import numpy as np

matrix = np.random.randint(1, 100, size=(5, 5))

print("Random 5x5 matrix:")
print(matrix)

min_row = np.min(matrix, axis=1)
max_row = np.max(matrix, axis=1)

print("\nMinimum values along each row:")
print(min_row)
print("\nMaximum values along each row:")
print(max_row)

min_col = np.min(matrix, axis=0)
max_col = np.max(matrix, axis=0)

print("\nMinimum values along each column:")
print(min_col)
print("\nMaximum values along each column:")
print(max_col)


Random 5x5 matrix:
[[98  2 62 15 74]
 [15 23 37 47 85]
 [37 41 26 14 94]
 [76 12 55 65 65]
 [48 94 35 18 90]]

Minimum values along each row:
[ 2 15 14 12 18]

Maximum values along each row:
[98 85 94 76 94]

Minimum values along each column:
[15  2 26 14 65]

Maximum values along each column:
[98 94 62 65 94]


In [11]:

import numpy as np

def cosine(a, b):
    dot_product = np.dot(a, b)
    a = np.linalg.norm(a)
    b = np.linalg.norm(b)
    similarity = dot_product / (a * b)
    return similarity

vector1 = np.array([11, 66, 33])
vector2 = np.array([55, 22, 44])

print("Cosine Similarity:", cosine(vector1, vector2))


Cosine Similarity: 0.6374011242825941
